version: 0.2

phases:
  pre_build:
    commands:
      - apt-get update
      - apt install software-properties-common
      - add-apt-repository ppa:ubuntu-toolchain-r/test
      - apt-get -y install libcurl4-openssl-dev g++-9 gcc-9

      # Confirm GCC install went through because it fails silently sometimes
      - echo $(ls /usr/bin/)
      - python3.8 -m pip install cpplint
      - start-dockerd
  build:
    commands:
      # prepare the release (update versions, changelog etc.)
      - git-release --prepare

      - tox -e flake8

      - python3.8 -m cpplint --linelength=120 --filter=-build/c++11,-build/header_guard --extensions=cpp,hpp --quiet --recursive src/

      # run tests
      - tox -e py37,py38 -- test/

      # generate the distribution package
      - python setup.py sdist
      - |
        PYTHON_VERSIONS="python3.8 python3.7"
        for PYTHON in ${PYTHON_VERSIONS}; do
          $PYTHON -m pip install -U pip
          $PYTHON -m pip install wheel tensorflow==2.8.0 twine==1.11 cmake
          $PYTHON setup.py build bdist_wheel --plat-name manylinux1_x86_64
        done;

      # publish the release to github
      - git-release --publish

artifacts:
  files:
    - dist/sagemaker_tensorflow-*-cp37-*.whl
    - dist/sagemaker_tensorflow-*-cp38-*.whl
  name: ARTIFACT_1
  discard-paths: yes
