version: 0.2

phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get -y install libcurl4-openssl-dev g++-5
      - pip install cpplint
      - start-dockerd

  build:
    commands:
      # prepare the release (update versions, changelog etc.)
      - git-release --prepare

      - tox -e flake8

      - cpplint --linelength=120 --filter=-build/c++11,-build/header_guard --extensions=cpp,hpp --quiet --recursive src/

      # run tests
      - tox -e py27,py36 -- test/

      # generate the distribution package
      - python setup.py sdist
      - |
        PYTHON_VERSIONS="python3.6 python2.7"
        for PYTHON in ${PYTHON_VERSIONS}; do
          $PYTHON -m pip install wheel tensorflow==1.15 twine==1.11 cmake
          $PYTHON setup.py build bdist_wheel --plat-name manylinux1_x86_64
        done;

      # publish the release to github
      - git-release --publish

artifacts:
  files:
    - dist/sagemaker_tensorflow-*-cp27-*.whl
    - dist/sagemaker_tensorflow-*-cp36-*.whl
  name: ARTIFACT_1
  discard-paths: yes
