version: 0.2

phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get -y install libcurl4-openssl-dev g++-9
      - python3.9 -m pip install cpplint
      - start-dockerd
  build:
    commands:
      - tox -e flake8

      - python3.9 -m cpplint --linelength=120 --filter=-build/c++11 --extensions=cpp,hpp --quiet --recursive src/

      - tox -e py37,py38,py39 -- test/
